script: bundle exec rspec
language: ruby
notifications:
  email: false
rvm:
  - 1.9
  - 2.0
  - 2.1
before_script:
  - "cd spec/dummy; bundle exec rake redde_seo_engine:install:migrations db:create db:migrate RAILS_ENV=test"
